sylius_resource:
    resources:
          app.image_banner:
            driver: doctrine/orm
            classes:
                model: App\Entity\ImageBanner
                form: App\Form\Type\ImageBannerType
